// TPAngular/src/app/components/detalle-instrumento/detalle-instrumento.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Instrumento } from 'src/app/entidades/Instrumento';
import { InstrumentoService } from 'src/app/servicios/instrumento.service';

@Component({
  selector: 'app-detalle-instrumento',
  templateUrl: './detalle-instrumento.component.html',
})
export class DetalleInstrumentoComponent implements OnInit {
  instrumento!: Instrumento;

  constructor(
    private ActivatedRoute: ActivatedRoute,
    private servicioInstrumento: InstrumentoService
  ) {
    this.ActivatedRoute.params.subscribe((params) => {
      this.servicioInstrumento
        .getInstrumentoEnBaseDatosXId(params['id'])
        .subscribe((instrumentoEncontrado) => {
          this.instrumento = instrumentoEncontrado as Instrumento;
        });
    });
  }

  ngOnInit(): void {}

  carrito() {
    alert("Carrito no disponible")
  }
}

<div class="row">
  <div class="col-md-4" style="text-align: center;">
    <img src="assets/img/{{instrumento.imagen}}" style="max-width: 300px;" class="img-fluid"
      [alt]="instrumento.instrumento">
    <p><b>Descripcion:</b> {{instrumento.descripcion}}</p>
    <br><br>

  </div>
  <div class="col-md-8">
    <p style="font-size: small; color:darkgray">{{instrumento.cantidadVendida}} vendidos</p>
    <h3>{{instrumento.instrumento}}</h3>
    <hr>
    <p style="font-size: xx-large;"> ${{instrumento.precio}}</p>
    <p><b>Marca:</b> {{instrumento.marca}}</p>
    <p><b>Modelo:</b>{{instrumento.modelo}}</p>

    <div>
      <!-- <span *ngIf="instrumento.costoEnvio == 'G'" style="color:red; font-weight: bold;">
        Es Bebida
      </span> -->
      <br>
      Costo Envio:
      <h5> <br>
        <span *ngIf="instrumento.costoEnvio == 'G'" style=" color: green;">
          <img src="assets/img/camion.png" />
          Envío Gratis a todo el País
        </span>
        <!--  <span *ngIf="instrumento.costoEnvio != 'G'" style="color: red">Costo de Envio Interior de Argentina: $
          {{instrumento.costoEnvio}}</span> -->
      </h5>
      <div class="container">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a (click)="carrito()" class="btn btn-outline-primary my-2 my-sm-0">Añadir al Carrito</a>

            <a [routerLink]="['/instrumento']" class="btn btn-outline-primary my-2 my-sm-0">Regresar</a>

          </li>
        </ul>

      </div>

    </div>
  </div>
</div>

// Tp6 Vue/proyectovue/src/views/DetalleInstrumento.vue
<template>
  <div>
    <b-container fluid style="max-width: 800px" >
 
       <b-row no-gutters >
     
      <b-col>
            <b-card-img :src="'/img/' + instrumentoEncontrado.imagen" alt="Image" style="min-height:80px; max-height:350px" >
            </b-card-img>
            <br/>
            <tr/>
             Descripcion:
             <b-card-text>{{ instrumentoEncontrado.descripcion }}</b-card-text>
      </b-col>
      

      <b-col>
          <b-card-text><p>{{ instrumentoEncontrado.cantidadVendida }} vendidos</p> </b-card-text>
        <b-card-body  :title="instrumentoEncontrado.instrumento">
            <b-card-text> <h3>$ {{ instrumentoEncontrado.precio }}</h3></b-card-text>
            <b-card-text>Marca: {{ instrumentoEncontrado.marca }} <br/> Modelo: {{ instrumentoEncontrado.modelo }}</b-card-text>
         
            <b-card-text style="color:green" v-if="instrumentoEncontrado.costoEnvio === 'G'"><img :src ="'/img/Camion.png'"/> Envio gratis</b-card-text>
            <b-card-text style="color:red" v-else>{{ `Costo de Envio Interior de Argentina: $ ${instrumentoEncontrado.costoEnvio}` }}</b-card-text>
            <b-col>
              <b-button href="/producto" variant="outline-primary">VOLVER</b-button>
               <b-button style="margin:1rem" href="" variant="outline-success">Agregar al Carrito</b-button>
            </b-col>      
          </b-card-body>
      </b-col>

    </b-row>
 
    </b-container>
  </div>
</template>

<script>
export default {
  name: "DetalleInstrumento",
  components: {},
  mounted() {
    this.getInstrumentoXID();
  },
  data() {
    return {
      instrumentoEncontrado: []
    };
  },
  methods: {
    async getInstrumentoXID() {
      const parametroId = this.$route.params.id;
      const res = await fetch("/instrumentos.json");
      const resJson = await res.json();
      console.log(resJson);
      this.instrumentoEncontrado = await resJson.instrumentos.find(
        instrumento => instrumento.id === parametroId
      );
      console.log(this.instrumentoEncontrado);
    }
  }
};
</script>
